// Auto-generated Go code from C++ source
// Generated by Hybrid Transpiler
//
// Expected output for stl_containers.cpp

package main

type DataProcessor struct {
	// Vector -> []T
	Numbers []int32
	Names   []string

	// Map -> map[K]V
	Scores map[string]int32

	// UnorderedMap -> map[K]V
	IdToName map[int32]string

	// Set -> map[T]bool
	UniqueIds map[int32]bool

	// String -> string
	Description string

	// Optional -> *T
	OptionalValue *int32
}

func NewDataProcessor() *DataProcessor {
	return &DataProcessor{
		Numbers:   make([]int32, 0),
		Names:     make([]string, 0),
		Scores:    make(map[string]int32),
		IdToName:  make(map[int32]string),
		UniqueIds: make(map[int32]bool),
		Description: "Data processor",
		OptionalValue: nil,
	}
}

// Vector operations
func (this *DataProcessor) AddNumber(n int32) {
	this.Numbers = append(this.Numbers, n)
}

func (this *DataProcessor) GetNumber(index uint) int32 {
	if int(index) < len(this.Numbers) {
		return this.Numbers[index]
	}
	return -1
}

func (this *DataProcessor) GetNumberCount() uint {
	return uint(len(this.Numbers))
}

// Map operations
func (this *DataProcessor) SetScore(name string, score int32) {
	this.Scores[name] = score
}

func (this *DataProcessor) GetScore(name string) int32 {
	if score, ok := this.Scores[name]; ok {
		return score
	}
	return 0
}

func (this *DataProcessor) HasScore(name string) bool {
	_, ok := this.Scores[name]
	return ok
}

// UnorderedMap operations
func (this *DataProcessor) RegisterUser(id int32, name string) {
	this.IdToName[id] = name
}

func (this *DataProcessor) GetUserName(id int32) string {
	if name, ok := this.IdToName[id]; ok {
		return name
	}
	return ""
}

// Set operations (using map[T]bool)
func (this *DataProcessor) AddUniqueId(id int32) {
	this.UniqueIds[id] = true
}

func (this *DataProcessor) HasUniqueId(id int32) bool {
	return this.UniqueIds[id]
}

func (this *DataProcessor) GetUniqueIdCount() uint {
	return uint(len(this.UniqueIds))
}

// Optional operations
func (this *DataProcessor) SetValue(value int32) {
	this.OptionalValue = &value
}

func (this *DataProcessor) ClearValue() {
	this.OptionalValue = nil
}

func (this *DataProcessor) HasValue() bool {
	return this.OptionalValue != nil
}

func (this *DataProcessor) GetValue() int32 {
	if this.OptionalValue != nil {
		return *this.OptionalValue
	}
	return -1
}

// String operations
func (this *DataProcessor) SetDescription(desc string) {
	this.Description = desc
}

func (this *DataProcessor) GetDescription() string {
	return this.Description
}

// Nested containers
type NestedDataStructure struct {
	// Vector of vectors -> [][]T
	Matrix [][]int32

	// Map of vectors -> map[K][]V
	DataSets map[string][]float64

	// Vector of maps -> []map[K]V
	Records []map[string]int32
}

func NewNestedDataStructure() *NestedDataStructure {
	return &NestedDataStructure{
		Matrix:   make([][]int32, 0),
		DataSets: make(map[string][]float64),
		Records:  make([]map[string]int32, 0),
	}
}

func (this *NestedDataStructure) AddRow(row []int32) {
	this.Matrix = append(this.Matrix, row)
}

func (this *NestedDataStructure) AddDataSet(name string, data []float64) {
	this.DataSets[name] = data
}

func (this *NestedDataStructure) AddRecord(record map[string]int32) {
	this.Records = append(this.Records, record)
}

func (this *NestedDataStructure) GetRowCount() uint {
	return uint(len(this.Matrix))
}

// Template -> Generic (Go 1.18+)
type Container[T any] struct {
	Items []T
}

func NewContainer[T any]() *Container[T] {
	return &Container[T]{
		Items: make([]T, 0),
	}
}

func (this *Container[T]) Add(item T) {
	this.Items = append(this.Items, item)
}

func (this *Container[T]) Get(index uint) T {
	return this.Items[index]
}

func (this *Container[T]) Size() uint {
	return uint(len(this.Items))
}

func (this *Container[T]) Empty() bool {
	return len(this.Items) == 0
}

func main() {
	processor := NewDataProcessor()

	// Add numbers
	processor.AddNumber(1)
	processor.AddNumber(2)
	processor.AddNumber(3)

	// Set scores
	processor.SetScore("Alice", 95)
	processor.SetScore("Bob", 87)

	// Register users
	processor.RegisterUser(1, "Alice")
	processor.RegisterUser(2, "Bob")

	// Add unique IDs
	processor.AddUniqueId(100)
	processor.AddUniqueId(200)
	processor.AddUniqueId(100) // Duplicate, map will only store once

	// Optional value
	processor.SetValue(42)
}
